---
sidebar: sidebar 
permalink: oci/add-credentials-oci.html 
keywords: permissions, policy, iam, iam role, role, granting, iam policy, iam user, access keys, arn, aws accounts, aws, aws profile, json, credentials, adding credentials, add credentials, oci nss, oracle cloud infrastructure 
summary: 'Aggiungi le credenziali di Oracle Cloud Infrastructure (OCI) in modo che Workload Factory disponga delle autorizzazioni necessarie per distribuire e gestire le risorse cloud nei tuoi account OCI.' 
---
= Aggiungi le credenziali di Oracle Cloud Infrastructure a NetApp Workload Factory
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Aggiungi e gestisci le credenziali del tuo cloud provider in modo che NetApp Workload Factory disponga delle autorizzazioni necessarie per distribuire e gestire le risorse nei tuoi account del cloud provider.

link:permissions-oci.html["Autorizzazioni per OCI NetApp Storage Service"]

.Informazioni su questa attività
Dalla pagina Credenziali puoi aggiungere le credenziali a un account Workload Factory esistente. In questo modo, Workload Factory disporrà delle autorizzazioni necessarie per gestire risorse e processi all'interno del tuo ambiente cloud.

.Prima di iniziare
Ti serviranno le credenziali per accedere al tuo account Oracle Cloud Infrastructure.

.Passaggi
. Accedi al  https://console.netapp.com/["Console NetApp"^].
. Dal menu, seleziona *Carichi di lavoro* > *Amministrazione* > *Credenziali*.
. Nella pagina Credenziali, seleziona *Aggiungi credenziali*.
. Nella pagina Aggiungi credenziali di Oracle Cloud Infrastructure NetApp Storage Service, procedi come segue:
+
.. In _Configurazione autorizzazioni_, seleziona le autorizzazioni appropriate per le credenziali di Oracle Cloud Infrastructure NetApp Storage Service. Le autorizzazioni *View, plan, and analyze* sono quelle predefinite. Questa policy di autorizzazioni ti consente di visualizzare i pool di storage OCI NSS, conoscere lo stato di salute del sistema, ottenere l'analisi well-architected per i tuoi sistemi ed esplorare i risparmi.
.. Segui i passaggi manuali forniti utilizzando Oracle Cloud Console per completare la configurazione delle autorizzazioni per le credenziali OCI NSS.
.. Nella sezione _Nome credenziali_, inserisci il nome che desideri utilizzare per queste credenziali e inserisci l'OCID del tenant.


. Seleziona *Aggiungi*.


.Cosa c'è dopo
link:quick-start-oci.html["Guida rapida per Oracle Cloud Infrastructure NetApp Storage Service in NetApp Workload Factory."]
