---
sidebar: sidebar 
permalink: gcnv/add-credentials.html 
keywords: permissions, policy, iam, iam role, role, granting, iam policy, iam user, access keys, arn, aws accounts, aws, aws profile, json, credentials, adding credentials, add credentials 
summary: Aggiungi le credenziali di Google Cloud NetApp Volumes in modo che Workload Factory disponga delle autorizzazioni necessarie per distribuire e gestire le risorse cloud nei tuoi account Google. 
---
= Aggiungi le credenziali di Google Cloud NetApp Volumes a NetApp Workload Factory
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Aggiungi e gestisci le credenziali del tuo cloud provider in modo che NetApp Workload Factory disponga delle autorizzazioni necessarie per distribuire e gestire le risorse nei tuoi account del cloud provider.



[[overview]]
== Panoramica

Puoi aggiungere le credenziali di Google Cloud NetApp Volumes dalla pagina Credenziali in NetApp console. La console fornisce istruzioni di configurazione guidata e un link alla documentazione, così puoi completare la configurazione Google Cloud richiesta e poi tornare a completare l'aggiunta delle credenziali.

Utilizza questo flusso di lavoro per concedere a Workload Factory le autorizzazioni necessarie per individuare, analizzare e gestire le risorse nel tuo ambiente Google Cloud.

La creazione delle credenziali si articola in tre parti:

* Passaggio 1: Seleziona il livello di autorizzazioni che desideri concedere a Workload Factory.
* Passaggio 2: crea e convalida un account di servizio Google Cloud, quindi seleziona il progetto Google Cloud da gestire.
* Passaggio 3: Inserisci un nome per le credenziali e aggiungi le credenziali.


.Prima di iniziare
Ti serviranno le credenziali per accedere al tuo account Google Cloud.

.Passaggi
. Accedi al  https://console.netapp.com/["Console NetApp"^].
. Dal menu, seleziona *Carichi di lavoro* > *Amministrazione* > *Credenziali*.
. Nella pagina Credenziali, seleziona *Aggiungi credenziali*.
. Seleziona *Google Cloud NetApp Volumes* come cloud provider.
. Nella pagina Aggiungi credenziali di Google Cloud NetApp Volumes, completa ogni sezione in *Configurazione delle autorizzazioni*.




[[step-1-create-permission-policies]]
=== Passaggio 1: Crea le policy di autorizzazione

.Passaggi
. In *Crea criteri di autorizzazione*, *Visualizza, pianifica e analizza* è selezionato per impostazione predefinita. Questo criterio di autorizzazione ti consente di visualizzare i pool di storage di Google Cloud NetApp Volumes, conoscere lo stato di salute del sistema, ottenere l'analisi well-architected per i tuoi sistemi ed esplorare i risparmi.
. Opzionale: seleziona *Operazioni e correzione* se vuoi che Workload Factory gestisca anche le risorse di Google Cloud NetApp Volumes e risolva i problemi di configurazione.
. Consulta le istruzioni di configurazione in link:https://docs.netapp.com/us-en/storage-management-google-cloud-netapp-volumes/task-set-up-gcnv.html#set-up-a-service-account["Configura Google Cloud NetApp Volumes"^] prima di continuare.




[[step-2-create-the-google-cloud-service-account]]
=== Passaggio 2: crea l'account di servizio Google Cloud

.Passaggi
. Espandi *Configura il tuo ambiente Google Cloud*.
. Completa i passaggi da 1 a 5 visualizzati per creare un account di servizio Google Cloud.
. Copia l'indirizzo email dell'account di servizio.
. Torna a Workload Factory, incolla l'indirizzo email nel campo *GCP service account* e seleziona *Validate credentials*.
. Una volta completata la convalida, dal menu a tendina *Projects*, seleziona il progetto Google Cloud che vuoi far gestire a Workload Factory. NOTA: l'elenco Projects non è disponibile finché le credenziali dell'account di servizio non sono state verificate.




[[step-3-enter-the-credentials-name]]
=== Passaggio 3: Inserisci il nome delle credenziali

.Passaggi
. Espandi *Nome delle credenziali*.
. Nel campo *Nome*, inserisci un nome per le credenziali utilizzando solo caratteri alfanumerici. I caratteri speciali e gli spazi non sono consentiti.
. Seleziona *Aggiungi*.


.Risultato
Le credenziali di Google Cloud NetApp Volumes vengono aggiunte al tuo account e sono disponibili per le operazioni supportate di Workload Factory.
