---
sidebar: sidebar 
permalink: fsx-eda/learn-eda-workloads.html 
keywords: software builders, development, benefits, eda, electronic design automation, perforce integration, ci, cd 
summary: 'Scopri come utilizzare l"integrazione di Perforce in NetApp Workload Factory per EDA.' 
---
= Scopri l'integrazione di Perforce in Workload Factory per EDA
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
L'integrazione di Perforce con le pipeline CI/CD migliora il processo di sviluppo automatizzando build, test e deployment, con un rilascio del software più rapido e affidabile.

L'integrazione continua e la distribuzione continua (CI/CD) in EDA sono uno strumento per la creazione rapida di ambienti di sviluppo per gli sviluppatori software. Consentono di configurare rapidamente ambienti di sviluppo personali, facendo risparmiare tempo e offrendo agli sviluppatori il self-service, mentre i team DevOps mantengono il controllo dell'infrastruttura. Con CI/CD, gli sviluppatori software possono creare rapidamente spazi di lavoro senza dover disporre di storage di dati specializzato né comprendere l'infrastruttura di sviluppo.



[[what-is-cicd]]
== Che cos'è CI/CD?

Grazie alla CI/CD, puoi semplificare il modo in cui gli sviluppatori gestiscono e interagiscono con le diverse versioni del loro software. Funziona con Perforce Helix Core per clonare istantaneamente le versioni del software e creare aree di lavoro per lo sviluppo, il controllo qualità e la CI/CD.

Puoi creare facilmente un progetto e assegnargli un volume che rappresenta il tuo ambiente software e i relativi artefatti. Quando aggiorni il software, puoi creare snapshot del volume, acquisendo lo stato del software in quel momento. Puoi accedere istantaneamente a qualsiasi versione del software senza risincronizzarla, risparmiando tempo e risorse.

Grazie alle funzionalità di snapshot e clonazione di NetApp ONTAP, puoi accedere rapidamente a diverse versioni del software, così puoi sviluppare e rilasciare aggiornamenti più velocemente. Per ulteriori informazioni su Workload Factory, consulta la documentazione link:https://docs.netapp.com/us-en/workload-setup-admin/workload-factory-overview.html["Panoramica di Workload Factory"^].



[[cicd-features]]
== Funzionalità CI/CD

* Crea, modifica e rimuovi progetti. Vedi link:manage-projects.html["Gestisci i progetti"].
* Crea snapshot di versioni software definite. Vedi link:version-projects.html["Gestisci le versioni del progetto"].
* Crea ed elimina aree di lavoro (basate su cloni). Vedi link:create-workspaces.html["Crea uno spazio di lavoro"].
* Crea criteri di accesso per controllare l'accesso a un progetto.
* Analizza l'utilizzo della capacità di ciascun progetto.
* Gestisci i limiti di dimensione dei cloni e la loro conservazione per ciascun progetto.
* Integra con sistemi di controllo della versione come Perforce. Vedi link:integrate-perforce.html["Integra con Perforce"].




[[projects-and-workspaces-in-eda]]
== Progetti e spazi di lavoro in EDA

Puoi creare un progetto e assegnargli un volume che rappresenta il tuo ambiente software e i relativi artefatti. Ogni volta che crei una nuova versione del software, devi risincronizzare i dati del volume e creare uno snapshot del progetto per contrassegnare lo stato del volume come una versione nota. Il volume di origine del progetto può ricevere aggiornamenti continui e avere più snapshot per contrassegnare più versioni. Puoi usare subito ogni snapshot come clone istantaneo, un repository modificabile dedicato o condiviso disponibile per sviluppatori, QA o processi di build. Un clone, nel contesto di una specifica versione del software, è un workspace.



[[automation-with-workload-factory-codebox]]
== Automazione con Workload Factory Codebox

Workload Factory introduce l'automazione integrata con _Codebox_. _Codebox_ offre i seguenti vantaggi in termini di automazione:

* *Generazione di snippet di codice*: gli snippet di Infrastructure-as-Code (IaC) si generano durante la creazione delle risorse, consentendoti di integrarli senza problemi nei flussi di lavoro di orchestrazione esistenti.
* *Co-pilot Infrastructure-as-code*: Codebox è un co-pilot Infrastructure-as-code (IaC) che aiuta gli sviluppatori e i team DevOps a generare codice per eseguire qualsiasi operazione supportata da Workload Factory.
* *Visualizzatore di codice e catalogo di automazione*: Codebox offre un visualizzatore di codice per un'analisi rapida dell'automazione e un catalogo di automazione per un rapido riutilizzo futuro.




[[cost]]
== Costo

L'utilizzo della funzionalità CI/CD di Workload Factory è gratuito.



[[licensing]]
== Licenze

Non sono necessarie licenze speciali da NetApp per utilizzare le funzionalità CI/CD di Workload Factory.



[[regions]]
== Regioni

EDA è supportato in tutte le regioni commerciali in cui è supportato FSx for ONTAP. https://aws.amazon.com/about-aws/global-infrastructure/regional-product-services/["Visualizza le regioni Amazon supportate."^]

Le seguenti regioni AWS non sono supportate:

* regioni della Cina
* Secret Cloud
* Top Secret Cloud




[[getting-help]]
== Come ottenere assistenza

Amazon FSx for NetApp ONTAP è una soluzione first-party di AWS. Per ricevere assistenza, utilizza il Support Center nella tua AWS Management Console per aprire un caso. Seleziona "FSx for ONTAP" e la categoria, quindi fornisci le informazioni richieste.

Per domande generali su Workload Factory o sulle applicazioni e i servizi di Workload Factory, consulta link:../get-help.html["Richiedi assistenza per EDA per Workload Factory"].
