---
sidebar: sidebar 
permalink: admin/configure-notifications.html 
keywords: amazon, sns, notification, topic, notifications, notifications service, alerts, email, email notifications, console notifications, filter, filtering 
summary: 'Puoi configurare NetApp Workload Factory per inviare notifiche a una persona o a un"altra applicazione quando si verificano determinati tipi di eventi.' 
---
= Configura le notifiche di NetApp Workload Factory
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile configurare il servizio di notifica NetApp Workload Factory per inviare notifiche come avvisi nella NetApp Console, a qualsiasi indirizzo email associato all'account o a un argomento Amazon SNS. Le notifiche inviate come avvisi vengono visualizzate nella NetApp Console quando è stato distribuito un agente o un collegamento Console. Quando Workload Factory pubblica notifiche su un argomento Amazon SNS, gli iscritti all'argomento (ad esempio, persone o altre applicazioni) ricevono le notifiche agli endpoint configurati per l'argomento (ad esempio, email o SMS).



[[configure-workload-factory-notifications]]
== Configura le notifiche di Workload Factory

È possibile configurare le notifiche di Workload Factory tramite NetApp Console o la console di Workload Factory.

Le opzioni per ricevere le notifiche includono:



[[netapp-console]]
=== NetApp Console

* *Notifiche*: Configura Workload Factory per inviare notifiche che vengono visualizzate sotto l'icona a forma di campana nella NetApp Console.
* *Email*: Abilita le notifiche e-mail in NetApp Console per ricevere notifiche a qualsiasi indirizzo e-mail associato all'account senza dover configurare Amazon SNS.
* *Amazon SNS*: Configura Workload Factory per inviare notifiche a un argomento Amazon SNS.




[[workload-factory-console]]
=== Console di Workload Factory

* *Email*: Abilita le notifiche e-mail nella console di Workload Factory per ricevere notifiche a qualsiasi indirizzo e-mail associato all'account senza dover configurare Amazon SNS.
* *Amazon SNS*: Configura Workload Factory per inviare notifiche a un argomento Amazon SNS tramite la NetApp Workload Factory console.



IMPORTANT: Quando si configurano le notifiche in NetApp Console, quest'ultima assume il controllo della distribuzione delle notifiche e le opzioni di notifica della console di Workload Factory vengono disabilitate e visualizzate in modalità di sola lettura. Un tooltip indica che le notifiche vengono gestite da NetApp Console. È quindi possibile gestire le notifiche esclusivamente da NetApp Console.

.Prima di iniziare
I seguenti prerequisiti si applicano solo durante la configurazione delle notifiche di Amazon SNS:

* Devi configurare Amazon SNS e creare argomenti Amazon SNS utilizzando la console Amazon SNS o l'AWS CLI.
* Tieni presente che Workload Factory supporta il tipo di argomento *Standard*. Questo tipo di argomento non garantisce che le notifiche vengano inviate agli iscritti nell'ordine in cui sono state ricevute, quindi valuta questa opzione se hai notifiche critiche o di emergenza.


[role="tabbed-block"]
====
.Configura le notifiche da NetApp Console
--
.Passaggi
. Accedi al link:https://console.netapp.com["NetApp Console"^].
. Dal menu NetApp Console, seleziona *Workloads*, *Administration* e quindi *Notifications setup*.
. Nella pagina di configurazione delle notifiche, abilita uno o più dei seguenti tipi di notifica:
+
.. *NetApp Console notifiche*: Seleziona *Abilita NetApp Console notifiche* per configurare Workload Factory in modo che invii notifiche in NetApp Console.
.. *Notifiche e-mail*: Seleziona *Abilita notifiche e-mail* per configurare Workload Factory in modo che invii notifiche a tutti gli indirizzi e-mail associati all'account.
.. *Notifiche Amazon SNS*: Seleziona *Abilita notifiche SNS*, quindi segui le istruzioni per configurare Amazon SNS dalla console Amazon SNS.
+
Dopo aver creato l'argomento, copia l'ARN dell'argomento e inseriscilo nel campo *SNS topic ARN* nella pagina *Notifications setup*.



. Dopo aver verificato la configurazione inviando una notifica di prova, seleziona *Applica*.


--
[[wf-console-email-notifications]]
.Configura le notifiche dalla console Workload Factory
--
.Passaggi
. Accedi al link:https://console.workloads.netapp.com["Console di Workload Factory"^].
. Dal menu della console di Workload Factory, seleziona *Workloads*, *Administration* e poi *Notifications setup*.
. Abilita uno o più dei seguenti tipi di notifica:
+
** *Notifiche via email*: Seleziona *Abilita notifiche via email*. Tutti gli indirizzi email associati all'account vengono visualizzati in modalità di sola lettura.
** *Notifiche Amazon SNS*: Seleziona *Abilita notifiche SNS*, quindi segui le istruzioni per configurare Amazon SNS dalla console Amazon SNS.
+
Dopo aver verificato la configurazione inviando una notifica di prova, seleziona *Applica*.





--
====


[[subscribe-to-the-amazon-sns-topic]]
== Iscriviti all'argomento Amazon SNS

Dopo aver configurato Workload Factory per inviare notifiche a un argomento, segui le https://docs.aws.amazon.com/sns/latest/dg/sns-create-subscribe-endpoint-to-topic.html["istruzioni"] nella documentazione di Amazon SNS per iscriverti all'argomento, così potrai ricevere notifiche da Workload Factory.



[[filter-notifications]]
== Filtra le notifiche

È possibile ridurre il traffico di notifiche non necessario e indirizzare tipi di notifiche specifici a utenti specifici applicando dei filtri alle notifiche. È possibile farlo utilizzando una policy Amazon SNS per le notifiche SNS e tramite le impostazioni delle notifiche nella NetApp Console.



[[filter-amazon-sns-notifications]]
=== Filtra le notifiche di Amazon SNS

Quando ti iscrivi a un topic di Amazon SNS, per impostazione predefinita ricevi tutte le notifiche pubblicate su quel topic. Se vuoi ricevere solo notifiche specifiche dal topic, puoi usare una policy di filtro per controllare quali notifiche ricevi. Le policy di filtro fanno sì che Amazon SNS invii al sottoscrittore solo le notifiche che corrispondono alla policy di filtro.

Puoi filtrare le notifiche di Amazon SNS in base ai seguenti criteri:

[cols="3*"]
|===
| Descrizione | Nome del campo della policy di filtro | Valori possibili 


| Tipo di risorsa | `resourceType`  a| 
* `DB`
* `Microsoft SQL Server host`
* `PostgreSQL Server host`




| Carico di lavoro | `workload` | `WLMDB` 


| Priorità | `priority`  a| 
* `Success`
* `Info`
* `Recommendation`
* `Warning`
* `Error`
* `Critical`




| Tipo di notifica | `notificationType`  a| 
* `Deployment`
* `Well-architected`


|===
.Passaggi
. Nella console di Amazon SNS, modifica i dettagli della sottoscrizione per l'argomento SNS.
. Nell'area *Criteri di filtro dell'abbonamento*, seleziona l'opzione per filtrare in base agli *Attributi del messaggio*.
. Abilita l'opzione *Criterio di filtro della sottoscrizione*.
. Inserisci una policy di filtro JSON nella casella *JSON editor*.
+
Ad esempio, la seguente policy di filtro JSON accetta notifiche dalla risorsa Microsoft SQL Server relative al carico di lavoro WLMDB, con priorità Success o Error, e fornisce dettagli sullo stato Well-architected:

+
[source, json]
----
{
  "accountId": [
    "account-a"
  ],
  "resourceType": [
    "Microsoft SQL Server host"
  ],
  "workload": [
    "WLMDB"
  ],
  "priority": [
    "Success",
    "Error"
  ],
  "notificationType": [
    "Well-architected"
  ]
}
----
. Seleziona *Salva modifiche*.


Per altri esempi di criteri di filtro, consulta https://docs.aws.amazon.com/sns/latest/dg/example-filter-policies.html["Esempi di policy di filtro per Amazon SNS"^].

Per ulteriori informazioni sulla creazione di criteri di filtro, consulta  https://docs.aws.amazon.com/sns/latest/dg/sns-message-filtering.html["Documentazione di Amazon SNS"^].



[[filter-notifications-in-netapp-console]]
=== Filtra le notifiche in NetApp Console

È possibile utilizzare le impostazioni delle notifiche della NetApp Console per filtrare le notifiche ricevute nella Console in base al livello di gravità, come Critico, Info o Avviso.

Per ulteriori informazioni sul filtraggio delle notifiche nella Console, consulta https://docs.netapp.com/us-en/console-setup-admin/task-monitor-cm-operations.html#filter-notifications["Documentazione di NetApp Console"^].



[[notification-types-and-messages]]
== Tipi di notifica e messaggi

Workload Factory invia notifiche per i seguenti eventi:

[cols="6*"]
|===
| Evento | Descrizione | Tipo di notifica | Gravità | Carico di lavoro | Tipo di risorsa 


| Alcune istanze di database nel tuo account non hanno un'architettura adeguata | Tutte le istanze di Microsoft SQL Server nel tuo account sono state analizzate per individuare problemi di architettura ottimale. La descrizione di questo evento indica il numero di istanze con architettura ottimale e di istanze non ottimizzate. Esamina i risultati e i consigli sullo stato dell'architettura ottimale nell'inventario Databases dalla console Workload Factory. | Ben progettato | Raccomandazione | Database | istanza di Microsoft SQL Server 


| Distribuzione del server Microsoft SQL Server/PostgreSQL riuscita | La distribuzione dell'host Microsoft SQL Server o PostgreSQL è stata completata correttamente. Per ulteriori informazioni, vai a monitoraggio processi. | Distribuzione | Successo | Database | FSx for ONTAP, host DB 


| Distribuzione del server Microsoft SQL Server/PostgreSQL non riuscita | La distribuzione dell'host Microsoft SQL Server o PostgreSQL non è riuscita. Per ulteriori informazioni, vai a monitoraggio processi. | Distribuzione | Errore | Database | FSx for ONTAP, host DB 


| Creazione della relazione di replica non riuscita | La creazione di una relazione di replica SnapMirror non è riuscita. Per ulteriori informazioni, vai a Tracker. | Replica | Critico | Storage generale | FSx for ONTAP 


| Errore durante la creazione di FSx for ONTAP | Il processo di creazione di un file system FSx per ONTAP non è riuscito. Per ulteriori informazioni, vai a Tracker. | Azione del file system FSx for ONTAP | Critico | Storage generale | FSx for ONTAP 


| Aumento automatico della capacità SSD o degli inode riuscito | Durante un recente aggiornamento automatico della gestione della capacità, il file system FSx for ONTAP ha aumentato correttamente la capacità SSD o gli inode del volume. Per ulteriori informazioni, vai a Tracker. | Gestione della capacità | Successo | Storage generale | file FSx for ONTAP 


| Errore nell'aumento automatico della capacità SSD o degli inode | Durante un recente aggiornamento automatico della gestione della capacità, il file system FSx for ONTAP non è riuscito ad aumentare la capacità SSD o gli inode del volume. Per ulteriori informazioni, vai a Tracker. | Gestione della capacità | Critico | Storage generale | FSx for ONTAP file system 


| Problema con FSx for ONTAP rilevato | Tutti i file system FSx for ONTAP sono stati analizzati per individuare problemi well-architected. La scansione ha rilevato uno o più problemi. Per ulteriori informazioni, consulta l'analisi well-architected nel dashboard Storage nella console di Workload Factory. | Analisi ben strutturata | Raccomandazione | Storage generale | FSx for ONTAP file system 


| Evento di gestione automatica della capacità per FSx for ONTAP | Il livello di prestazioni SSD per il file system FSx for ONTAP ha raggiunto la soglia di avviso per capacità/percentuale totale. | Gestione della capacità | Avvertimento | Storage generale | FSx for ONTAP file system 


| Evento automatico di gestione degli inode per FSx for ONTAP | Il conteggio degli inode per il volume FSx for ONTAP ha raggiunto la soglia di avviso in termini di conteggio/% totale. | Gestione della capacità | Avvertimento | Storage generale | FSx for ONTAP file system 


| Attività sospetta sui volumi rilevata in FSx for ONTAP file system | NetApp Autonomous Ransomware Protection con intelligenza artificiale (ARP/AI) ha rilevato attività sospette sul volume. | Protezione contro i ransomware | Critico | Storage generale | FSx for ONTAP file system 


| Rilevata violazione della soglia di latenza | Uno o più volumi nel cluster FSx for ONTAP hanno superato la soglia di latenza. | Monitoraggio delle prestazioni | Avvertimento | EDA | FSx for ONTAP file system 


| Rapporto mensile sui costi | Riepilogo mensile dei costi per il tuo account, con indicazione delle tendenze di spesa, delle variazioni anomale e delle migliori opportunità di risparmio per FSx for ONTAP file systems. | Rapporto sui costi | Raccomandazione | Storage generale | FSx for ONTAP file system 


| Ritardo di replica | La replicazione sta richiedendo più tempo del previsto. | Replica | Critico | Storage generale | FSx for ONTAP file system 


| Creazione dashboard personalizzato riuscita | La tua dashboard personalizzata è stata creata correttamente ed è pronta per essere visualizzata. | Cruscotti personalizzati | Successo | Storage generale | Account Workload Factory 


| Creazione dashboard personalizzata non riuscita | Workload Factory non è riuscita a creare la tua dashboard personalizzata. Prova a creare di nuovo la dashboard. | Cruscotti personalizzati | Errore | Storage generale | Account Workload Factory 
|===