---
sidebar: sidebar 
permalink: fsx-vmware/deploy-fsx-file-system.html 
keywords: vm workloads, deploy fsx, deploy storage for vms 
summary: Dopo aver verificato che il file system FSx for ONTAP consigliato, o i file system in alcuni casi, soddisfi esattamente i tuoi requisiti, puoi usare Workload Factory per distribuire il sistema nel tuo ambiente AWS. 
---
= Distribuisci il file system FSx per ONTAP consigliato
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Dopo aver verificato che il file system FSx for ONTAP consigliato (o, in alcuni casi, più file system) soddisfi esattamente i tuoi requisiti, puoi usare Workload Factory per distribuire il sistema nel tuo ambiente AWS.

A seconda delle policy e delle autorizzazioni che hai aggiunto al tuo account Workload Factory, puoi implementare completamente il file system FSx for ONTAP utilizzando Workload Factory (in modalità lettura/scrittura). Se hai meno autorizzazioni (modalità di sola lettura) o nessuna autorizzazione (modalità Basic), dovrai usare le informazioni CloudFormation del Codebox e implementare tu stesso il file system FSx for ONTAP in AWS.

.Requisiti per le implementazioni su VMware Cloud on AWS
* Per implementare i file system FSx for ONTAP, devi usare VMware Cloud on AWS Software-Defined Data Center (SDDC) versione 1.20 o successiva.
* Non devi distribuire il file system FSx for ONTAP nella stessa VPC utilizzata durante la distribuzione di SDDC. Devi invece distribuirlo in una nuova Amazon VPC di tua proprietà per abilitare l'integrazione di VMware Cloud on AWS con Amazon FSx for NetApp ONTAP.
* Devi distribuire il file system FSx for ONTAP nella stessa regione AWS del tuo SDDC.


.Passaggi
. In fondo alla pagina *Rivedi il piano*, seleziona *Distribuisci* e viene visualizzata la pagina Crea un file system FSx for ONTAP.
+
La maggior parte dei campi che definiscono il file system FSx for ONTAP viene completata in base alle informazioni che hai fornito, ma in questa pagina devi compilare ancora alcuni campi.

+
Puoi utilizzare l'opzione Creazione rapida o Creazione avanzata. Creazione avanzata offre alcuni parametri di archiviazione aggiuntivi che puoi personalizzare. link:../fsx-storage/create-discover-systems.html["Scopri cosa offrono queste due opzioni"].

. *Credenziali AWS*: seleziona o aggiungi le credenziali che forniranno a Workload Factory le autorizzazioni necessarie per creare direttamente il tuo FSx for ONTAP file system. Puoi anche selezionare il codice CloudFormation da Codebox e distribuire tu stesso il FSx for ONTAP file system in AWS.
. *Nome del file system*: Inserisci il nome che desideri utilizzare per questo file system FSx for ONTAP.
. *Tag*: Facoltativamente, puoi aggiungere tag per categorizzare questo file system FSx for ONTAP.
. Nella sezione "Rete e sicurezza", inserisci le seguenti informazioni:
+
.. *Regione e VPC*: Seleziona la regione e la VPC in cui verrà distribuito il file system FSx for ONTAP.
+
Se esegui il deployment su VMware Cloud on AWS, assicurati di distribuirlo in una VPC diversa dalla VPC in cui è distribuito VMware Cloud on AWS.

.. *Gruppo di sicurezza*: Quando usi l'opzione *Advanced create*, puoi selezionare il gruppo di sicurezza predefinito per la FSx for ONTAP VPC in modo che tutto il traffico possa accedere al FSx for ONTAP file system.
+
Puoi aggiungere una regola in entrata che limiti l'accesso di altri servizi AWS al file system FSx for ONTAP. Questo ridurrà il numero di servizi aperti. Queste sono le porte e i protocolli minimi richiesti:

+
[cols="15,10,55"]
|===
| Protocolli | Porte | Scopo 


| TCP, UDP | 111 | Portmapper (utilizzato per negoziare quali porte vengono utilizzate nelle richieste NFS) 


| TCP, UDP | 635 | NFS mountd (riceve richieste di montaggio NFS) 


| TCP, UDP | 2049 | traffico di rete NFS 


| TCP, UDP | 4045 | Network Lock Manager (NLM, lockd) - Gestisce le richieste di blocco. 


| TCP, UDP | 4046 | Network Status Monitor (NSM, statd) - Notifica ai client NFS i riavvii del server per la gestione dei lock. 
|===
.. *Zona di disponibilità*: Seleziona la zona di disponibilità e la sottorete.
+
Se vuoi evitare costi per il traffico tra zone di disponibilità diverse, devi selezionare la stessa zona di disponibilità in cui è distribuito VMware SDDC.

.. *Crittografia*: Quando usi l'opzione *Advanced create*, puoi selezionare il nome della chiave di crittografia AWS dal menu a discesa.
.. *Controllo dell'accesso al datastore*: quando utilizzi l'opzione *Creazione avanzata*, puoi selezionare se tutti gli host possono accedere ai datastore oppure se solo determinati nodi del cluster vSphere su una sottorete specifica possono accedervi.


. Nella sezione "Dettagli del file system", inserisci le seguenti informazioni:
+
.. *Credenziali ONTAP*: Inserisci e conferma la password di ONTAP.
.. *Credenziali della VM di storage* (solo per la creazione avanzata): immetti e conferma la password della VM di storage. La password può essere specifica per questo file system oppure puoi utilizzare la stessa password immessa per le credenziali ONTAP.


. Nella sezione *Riepilogo*, puoi visualizzare la configurazione del file system FSx per ONTAP e del datastore progettata da VMware Migration Advisor in base alle informazioni che hai fornito.
. Seleziona *Crea* per distribuire il file system FSx for ONTAP. Questo processo può richiedere fino a 2 ore.
+
Facoltativamente, nella finestra Codebox puoi selezionare *Reindirizza a CloudFormation* per creare il file system utilizzando uno stack di CloudFormation.

+
In entrambi i casi, puoi monitorare l'avanzamento della creazione in CloudFormation.



.Risultato
Il file system FSx for ONTAP è stato distribuito.
