---
sidebar: sidebar 
permalink: fsx-vmware/learn-about-vmware-workloads.html 
keywords: overview, concepts, features, use case, workloads, how Workload Factory works 
summary: 'NetApp Workload Factory per VMware fornisce strumenti per spostare i dati dai sistemi on-premises ad Amazon EVS, VMware Cloud on AWS (VMC), Amazon EC2 o Google Cloud VMware Engine.' 
---
= Scopri di più su NetApp Workload Factory for VMware
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
NetApp Workload Factory per VMware fornisce strumenti per spostare i dati dai sistemi on-premises ad Amazon Elastic VMware Service (EVS), VMware Cloud on AWS (VMC), Amazon EC2 o Google Cloud VMware Engine.



[[what-is-netapp-workload-factory-for-vmware]]
== Che cos'è NetApp Workload Factory per VMware?

NetApp Workload Factory per VMware offre un centro di pianificazione e consulenti per la migrazione che consentono di analizzare le attuali configurazioni delle macchine virtuali negli ambienti vSphere on-premises. I consulenti per la migrazione generano quindi un piano per distribuire i layout di VM consigliati su Amazon EVS, Amazon EC2, VMware Cloud on AWS vSphere cluster o Google Cloud VMware Engine, utilizzando storage cloud-native personalizzato come datastore esterni. Per gli ambienti AWS, questo include Amazon FSx for NetApp ONTAP file system. Per gli ambienti Google Cloud, questo include Google Cloud NetApp Volumes. Il centro di pianificazione, che funge da dashboard di Workload Factory per VMware, consente di gestire i set di dati di inventario delle VM salvati e i piani di migrazione salvati, nonché di effettuare il provisioning di qualsiasi piano di migrazione salvato.

Amazon FSx for NetApp ONTAP è un datastore NFS esterno basato sul file system ONTAP di NetApp che può essere collegato a istanze Amazon EVS o Amazon EC2 o a cluster VMware Cloud on AWS vSphere. Analogamente, Google Cloud NetApp Volumes fornisce datastore NFS esterni per ambienti Google Cloud VMware Engine. Non è necessario aggiungere altri host per aumentare lo storage disponibile; basta utilizzare questi volumi di storage cloud-native come datastore esterni per integrare i datastore vSAN. Questo offre un'infrastruttura di storage virtualizzata flessibile e dalle performance elevate, che si scala indipendentemente dalle risorse di elaborazione.

Per ulteriori informazioni su Workload Factory, consulta link:../setup/learn-about-workload-factory.html["Panoramica di Workload Factory"^].



[[how-the-vmware-migration-advisors-work]]
== Come funzionano i consulenti per la migrazione di VMware

I consulenti per la migrazione possono aiutarti a spostare macchine virtuali (VM) locali e i relativi dati, in esecuzione su qualsiasi datastore supportato da VMware, su datastore Amazon EVS, Amazon EC2, VMware Cloud o Google Cloud VMware Engine, che includono datastore NFS supplementari su un file system FSx for ONTAP o Google Cloud NetApp Volumes.

Tieni presente che puoi collegare fino a quattro (4) volumi FSx for ONTAP a un singolo cluster vSphere su VMware Cloud on AWS.



[[what-you-can-do-with-the-migration-advisors]]
== Cosa puoi fare con i consulenti per la migrazione

I consulenti per la migrazione offrono le seguenti funzionalità:

* Analizza le configurazioni attuali delle VM on-premises
* Determina quali VM migrare su Amazon EC2, Amazon EVS, VMware Cloud on AWS o Google Cloud VMware Engine
* Identificare lo spazio richiesto sui volumi di storage cloud-native da utilizzare come datastore esterni VM
* Esamina il report risultante per comprendere le fasi di implementazione
* Eseguire la distribuzione effettiva (per Amazon EC2, Amazon EVS e VMware Cloud on AWS)


Il consulente per la migrazione supporta la pianificazione della configurazione per un singolo Amazon EVS, Amazon EC2 o cluster VMware Cloud on AWS connesso ai file system Amazon FSx for NetApp ONTAP, o un cluster Google Cloud VMware Engine connesso a Google Cloud NetApp Volumes.



[[benefits-of-using-the-migration-advisors]]
== Vantaggi dell'utilizzo dei consulenti per la migrazione

La transizione di parti della tua infrastruttura attuale ad Amazon EC2, Amazon EVS, VMware Cloud on AWS o Google Cloud VMware Engine utilizzando storage cloud-native come datastore NFS esterni offre i seguenti vantaggi:

* Ottimizzazione dei costi grazie al disaccoppiamento tra host e storage e all'efficienza avanzata dei dati
* Possibilità di aumentare la capacità di storage in base alle necessità senza dover acquistare istanze host aggiuntive
* NetApp ONTAP funzionalità di gestione dei dati nel cloud, come snapshot efficienti in termini di spazio, clonazione, compressione, deduplicazione, compaction e replica
* Riduzione della gestione degli aggiornamenti hardware
* Possibilità di modificare il throughput dei dati, gli IOPS e le dimensioni del file system, oltre ad aumentare o diminuire le dimensioni dei volumi
* Elevata disponibilità che supporta implementazioni in più Availability Zone (AZ)
* Riduzione dei costi e della latenza grazie alle configurazioni a singola zona di disponibilità (AZ) che utilizzano il peering VPC senza richiedere un Transit Gateway




[[tools-to-use-netapp-workload-factory]]
== Strumenti per usare NetApp Workload Factory

Puoi utilizzare NetApp Workload Factory con i seguenti strumenti:

* *Console di Workload Factory*: La console di Workload Factory offre una panoramica visiva e completa delle tue applicazioni e dei tuoi progetti.
* *NetApp Console*: La NetApp Console offre un'esperienza di interfaccia ibrida, così puoi utilizzare Workload Factory insieme ad altri servizi dati NetApp.
* *Ask me*: Usa l'assistente AI Ask me per fare domande e saperne di più su Workload Factory senza uscire dalla console di Workload Factory. Accedi ad Ask me dal menu della guida di Workload Factory.
* *CloudShell CLI*: Workload Factory include una CLI CloudShell per gestire e utilizzare ambienti AWS e NetApp tra account da un'unica CLI basata su browser. Accedi a CloudShell dalla barra superiore della console di Workload Factory.
* *API REST*: utilizza le API REST di Workload Factory per distribuire e gestire i tuoi file system FSx for ONTAP e altre risorse AWS.
* *CloudFormation*: Utilizza il codice AWS CloudFormation per eseguire le azioni che hai definito nella console di Workload Factory per modellare, predisporre e gestire risorse AWS e di terze parti dallo stack CloudFormation nel tuo account AWS.
* *NetApp Terraform provider*: Usa Terraform per creare e gestire i workflow di infrastruttura generati nella console di Workload Factory.




[[well-architected-analysis-for-evs-environments]]
== Analisi well-architected per ambienti EVS

La scheda Well-architected fornisce un'analisi giornaliera automatizzata degli ambienti Amazon Elastic VMware Service (EVS) per garantirne l'allineamento con le best practice di AWS e NetApp. La scheda identifica i problemi di configurazione e fornisce indicazioni dettagliate per la risoluzione, aiutandoti a mantenere operatività, sicurezza ed efficienza dei costi ottimali.

Le scansioni automatiche vengono eseguite utilizzando le API AWS—non sono necessarie credenziali vSphere. I risultati sono organizzati per area di configurazione, con ogni risultato che include stato, livelli di gravità, dettagli sulle risorse interessate e procedure di risoluzione dettagliate passo dopo passo.

link:view-evs-well-architected.html["Implementare configurazioni EVS ben architettate in Workload Factory"].



[[cost]]
== Costo

L'utilizzo di Workload Factory for VMware è gratuito.

Dovrai pagare le risorse AWS che distribuirai in base ai consigli dei consulenti per la migrazione.



[[licensing]]
== Licenze

Non sono necessarie licenze speciali da NetApp per utilizzare Workload Factory per VMware.



[[regions]]
== Regioni

Workload Factory è supportato in tutte le regioni commerciali in cui è supportato FSx for ONTAP. https://aws.amazon.com/about-aws/global-infrastructure/regional-product-services/["Visualizza le regioni Amazon supportate."^]

Le seguenti regioni AWS non sono supportate:

* regioni della Cina
* Secret Cloud
* Top Secret Cloud

